// Code generated by goyacc -o parser.go -p Yy parser.y. DO NOT EDIT.

//line parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser.y:2

import "github.com/Meduza3/imp/token"

type YySymType struct {
	Token *token.Token
	yys   int
}

const ILLEGAL = 57346
const EOF = 57347
const PROCEDURE = 57348
const IS = 57349
const BEGIN = 57350
const END = 57351
const PROGRAM = 57352
const ASSIGN = 57353
const SEMICOLON = 57354
const IF = 57355
const THEN = 57356
const ELSE = 57357
const ENDIF = 57358
const WHILE = 57359
const DO = 57360
const ENDWHILE = 57361
const REPEAT = 57362
const UNTIL = 57363
const FOR = 57364
const FROM = 57365
const TO = 57366
const DOWNTO = 57367
const ENDFOR = 57368
const READ = 57369
const WRITE = 57370
const LPAREN = 57371
const RPAREN = 57372
const COMMA = 57373
const LBRACKET = 57374
const RBRACKET = 57375
const COLON = 57376
const T = 57377
const PLUS = 57378
const MINUS = 57379
const MULT = 57380
const DIVIDE = 57381
const MODULO = 57382
const EQUALS = 57383
const NEQUALS = 57384
const GE = 57385
const LE = 57386
const GEQ = 57387
const LEQ = 57388
const NUM = 57389
const PIDENTIFIER = 57390

var YyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ILLEGAL",
	"EOF",
	"PROCEDURE",
	"IS",
	"BEGIN",
	"END",
	"PROGRAM",
	"ASSIGN",
	"SEMICOLON",
	"IF",
	"THEN",
	"ELSE",
	"ENDIF",
	"WHILE",
	"DO",
	"ENDWHILE",
	"REPEAT",
	"UNTIL",
	"FOR",
	"FROM",
	"TO",
	"DOWNTO",
	"ENDFOR",
	"READ",
	"WRITE",
	"LPAREN",
	"RPAREN",
	"COMMA",
	"LBRACKET",
	"RBRACKET",
	"COLON",
	"T",
	"PLUS",
	"MINUS",
	"MULT",
	"DIVIDE",
	"MODULO",
	"EQUALS",
	"NEQUALS",
	"GE",
	"LE",
	"GEQ",
	"LEQ",
	"NUM",
	"PIDENTIFIER",
}

var YyStatenames = [...]string{}

const YyEofCode = 1
const YyErrCode = 2
const YyInitialStackSize = 16

//line parser.y:122

//line yacctab:1
var YyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const YyPrivate = 57344

const YyLast = 302

var YyAct = [...]int{
	22, 45, 47, 24, 80, 79, 23, 25, 43, 118,
	26, 15, 27, 21, 83, 78, 131, 29, 30, 12,
	47, 50, 41, 66, 67, 68, 69, 70, 71, 34,
	60, 46, 46, 38, 48, 41, 52, 46, 31, 41,
	49, 18, 39, 59, 37, 7, 120, 57, 24, 46,
	41, 13, 25, 106, 17, 26, 105, 27, 41, 13,
	84, 130, 29, 30, 56, 81, 124, 44, 86, 87,
	88, 89, 90, 46, 46, 46, 46, 46, 46, 91,
	46, 46, 99, 31, 119, 104, 98, 103, 54, 55,
	62, 55, 41, 46, 46, 46, 46, 46, 53, 41,
	101, 102, 35, 36, 33, 32, 10, 74, 19, 127,
	64, 116, 117, 126, 42, 72, 65, 115, 85, 76,
	75, 51, 41, 46, 46, 9, 121, 20, 4, 41,
	41, 20, 5, 11, 92, 93, 94, 95, 96, 97,
	128, 129, 100, 14, 8, 77, 16, 28, 63, 6,
	3, 2, 1, 0, 107, 108, 109, 110, 111, 24,
	0, 112, 113, 25, 0, 0, 26, 0, 27, 0,
	0, 0, 24, 29, 30, 125, 25, 0, 0, 26,
	0, 27, 0, 0, 122, 123, 29, 30, 0, 24,
	0, 0, 0, 25, 31, 114, 26, 82, 27, 0,
	0, 24, 0, 29, 30, 25, 0, 31, 26, 0,
	27, 0, 0, 24, 0, 29, 30, 25, 0, 0,
	26, 73, 27, 0, 31, 0, 61, 29, 30, 0,
	24, 0, 0, 0, 25, 0, 31, 26, 58, 27,
	0, 0, 24, 0, 29, 30, 25, 0, 31, 26,
	40, 27, 0, 0, 24, 0, 29, 30, 25, 0,
	0, 26, 0, 27, 0, 31, 24, 0, 29, 30,
	25, 0, 0, 26, 0, 27, 0, 31, 0, 0,
	29, 30, 0, 0, 0, 0, 0, 0, 0, 31,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 31,
}

var YyPact = [...]int{
	-1000, -1000, 122, -1000, -3, 137, 118, 77, 11, 3,
	6, 100, 253, 73, 96, 253, 72, -1000, -4, 253,
	-6, 241, -1000, 103, -46, -46, 253, -27, 109, -28,
	-46, 59, 17, 253, 229, -1000, -5, -1000, 217, 58,
	-1000, -1000, -46, 102, -18, -1000, -1000, 57, 97, 200,
	84, -1000, 108, 107, -33, -43, 31, 188, -1000, -1000,
	-34, -1000, 13, 106, 32, 253, -46, -46, -46, -46,
	-46, -46, 253, -46, -46, -1000, -1000, 70, -1000, 54,
	52, 9, -1000, -1000, 19, -1000, -46, -46, -46, -46,
	-46, 146, -1000, -1000, -1000, -1000, -1000, -1000, 176, 105,
	87, -1000, -39, -1000, -1000, 51, -1, -1000, -1000, -1000,
	-1000, -1000, 253, -1000, -1000, -1000, -46, -46, -1000, -1000,
	33, 159, 95, 91, -1000, -1000, 253, 253, 35, -10,
	-1000, -1000,
}

var YyPgo = [...]int{
	0, 152, 151, 150, 149, 133, 13, 0, 6, 148,
	8, 67, 147, 146, 145,
}

var YyR1 = [...]int{
	0, 1, 2, 2, 2, 3, 3, 6, 6, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 4,
	12, 5, 5, 5, 5, 13, 13, 13, 13, 14,
	14, 9, 9, 9, 9, 9, 9, 10, 10, 10,
	10, 10, 10, 11, 11, 8, 8, 8,
}

var YyR2 = [...]int{
	0, 2, 8, 7, 0, 6, 5, 2, 1, 4,
	7, 5, 5, 5, 9, 9, 2, 3, 3, 4,
	4, 3, 8, 1, 6, 3, 4, 1, 2, 3,
	1, 1, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 1, 1, 1, 4, 4,
}

var YyChk = [...]int{
	-1000, -1, -2, -3, 6, 10, -4, 48, 7, 7,
	29, -5, 8, 48, -5, 8, -13, 48, 35, 8,
	31, -6, -7, -8, 13, 17, 20, 22, -12, 27,
	28, 48, 32, 8, -6, 30, 31, 48, -6, 48,
	9, -7, 11, -10, -11, 47, -8, 48, -10, -6,
	48, 12, -8, -11, 29, 32, 47, -6, 9, 48,
	35, 9, 32, -9, -11, 14, 41, 42, 43, 44,
	45, 46, 18, 21, 23, 12, 12, -14, 48, 48,
	47, 34, 9, 48, 47, 12, 36, 37, 38, 39,
	40, -6, -11, -11, -11, -11, -11, -11, -6, -10,
	-11, 30, 31, 33, 33, 47, 34, -11, -11, -11,
	-11, -11, 15, 16, 19, 12, 24, 25, 48, 33,
	47, -6, -11, -11, 33, 16, 18, 18, -6, -6,
	26, 26,
}

var YyDef = [...]int{
	4, -2, 0, 1, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 23, 0, 0, 0, 27, 0, 0,
	0, 0, 8, 0, 0, 0, 0, 0, 0, 0,
	0, 45, 0, 0, 0, 19, 0, 28, 0, 21,
	6, 7, 0, 0, 0, 43, 44, 45, 0, 0,
	0, 16, 0, 0, 0, 0, 0, 0, 3, 25,
	0, 5, 0, 0, 31, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 17, 18, 0, 30, 0,
	0, 0, 2, 26, 0, 9, 0, 0, 0, 0,
	0, 0, 37, 38, 39, 40, 41, 42, 0, 0,
	0, 20, 0, 46, 47, 0, 0, 32, 33, 34,
	35, 36, 0, 11, 12, 13, 0, 0, 29, 24,
	0, 0, 0, 0, 22, 10, 0, 0, 0, 0,
	14, 15,
}

var YyTok1 = [...]int{
	1,
}

var YyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48,
}

var YyTok3 = [...]int{
	0,
}

var YyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	YyDebug        = 0
	YyErrorVerbose = false
)

type YyLexer interface {
	Lex(lval *YySymType) int
	Error(s string)
}

type YyParser interface {
	Parse(YyLexer) int
	Lookahead() int
}

type YyParserImpl struct {
	lval  YySymType
	stack [YyInitialStackSize]YySymType
	char  int
}

func (p *YyParserImpl) Lookahead() int {
	return p.char
}

func YyNewParser() YyParser {
	return &YyParserImpl{}
}

const YyFlag = -1000

func YyTokname(c int) string {
	if c >= 1 && c-1 < len(YyToknames) {
		if YyToknames[c-1] != "" {
			return YyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func YyStatname(s int) string {
	if s >= 0 && s < len(YyStatenames) {
		if YyStatenames[s] != "" {
			return YyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func YyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !YyErrorVerbose {
		return "syntax error"
	}

	for _, e := range YyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + YyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := YyPact[state]
	for tok := TOKSTART; tok-1 < len(YyToknames); tok++ {
		if n := base + tok; n >= 0 && n < YyLast && YyChk[YyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if YyDef[state] == -2 {
		i := 0
		for YyExca[i] != -1 || YyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; YyExca[i] >= 0; i += 2 {
			tok := YyExca[i]
			if tok < TOKSTART || YyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if YyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += YyTokname(tok)
	}
	return res
}

func Yylex1(lex YyLexer, lval *YySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = YyTok1[0]
		goto out
	}
	if char < len(YyTok1) {
		token = YyTok1[char]
		goto out
	}
	if char >= YyPrivate {
		if char < YyPrivate+len(YyTok2) {
			token = YyTok2[char-YyPrivate]
			goto out
		}
	}
	for i := 0; i < len(YyTok3); i += 2 {
		token = YyTok3[i+0]
		if token == char {
			token = YyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = YyTok2[1] /* unknown char */
	}
	if YyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", YyTokname(token), uint(char))
	}
	return char, token
}

func YyParse(Yylex YyLexer) int {
	return YyNewParser().Parse(Yylex)
}

func (Yyrcvr *YyParserImpl) Parse(Yylex YyLexer) int {
	var Yyn int
	var YyVAL YySymType
	var YyDollar []YySymType
	_ = YyDollar // silence set and not used
	YyS := Yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Yystate := 0
	Yyrcvr.char = -1
	Yytoken := -1 // Yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Yystate = -1
		Yyrcvr.char = -1
		Yytoken = -1
	}()
	Yyp := -1
	goto Yystack

ret0:
	return 0

ret1:
	return 1

Yystack:
	/* put a state and value onto the stack */
	if YyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", YyTokname(Yytoken), YyStatname(Yystate))
	}

	Yyp++
	if Yyp >= len(YyS) {
		nyys := make([]YySymType, len(YyS)*2)
		copy(nyys, YyS)
		YyS = nyys
	}
	YyS[Yyp] = YyVAL
	YyS[Yyp].yys = Yystate

Yynewstate:
	Yyn = YyPact[Yystate]
	if Yyn <= YyFlag {
		goto Yydefault /* simple state */
	}
	if Yyrcvr.char < 0 {
		Yyrcvr.char, Yytoken = Yylex1(Yylex, &Yyrcvr.lval)
	}
	Yyn += Yytoken
	if Yyn < 0 || Yyn >= YyLast {
		goto Yydefault
	}
	Yyn = YyAct[Yyn]
	if YyChk[Yyn] == Yytoken { /* valid shift */
		Yyrcvr.char = -1
		Yytoken = -1
		YyVAL = Yyrcvr.lval
		Yystate = Yyn
		if Errflag > 0 {
			Errflag--
		}
		goto Yystack
	}

Yydefault:
	/* default state action */
	Yyn = YyDef[Yystate]
	if Yyn == -2 {
		if Yyrcvr.char < 0 {
			Yyrcvr.char, Yytoken = Yylex1(Yylex, &Yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if YyExca[xi+0] == -1 && YyExca[xi+1] == Yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Yyn = YyExca[xi+0]
			if Yyn < 0 || Yyn == Yytoken {
				break
			}
		}
		Yyn = YyExca[xi+1]
		if Yyn < 0 {
			goto ret0
		}
	}
	if Yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Yylex.Error(YyErrorMessage(Yystate, Yytoken))
			Nerrs++
			if YyDebug >= 1 {
				__yyfmt__.Printf("%s", YyStatname(Yystate))
				__yyfmt__.Printf(" saw %s\n", YyTokname(Yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Yyp >= 0 {
				Yyn = YyPact[YyS[Yyp].yys] + YyErrCode
				if Yyn >= 0 && Yyn < YyLast {
					Yystate = YyAct[Yyn] /* simulate a shift of "error" */
					if YyChk[Yystate] == YyErrCode {
						goto Yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if YyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", YyS[Yyp].yys)
				}
				Yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if YyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", YyTokname(Yytoken))
			}
			if Yytoken == YyEofCode {
				goto ret1
			}
			Yyrcvr.char = -1
			Yytoken = -1
			goto Yynewstate /* try again in the same state */
		}
	}

	/* reduction by production Yyn */
	if YyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Yyn, YyStatname(Yystate))
	}

	Yynt := Yyn
	Yypt := Yyp
	_ = Yypt // guard against "declared and not used"

	Yyp -= YyR2[Yyn]
	// Yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Yyp+1 >= len(YyS) {
		nyys := make([]YySymType, len(YyS)*2)
		copy(nyys, YyS)
		YyS = nyys
	}
	YyVAL = YyS[Yyp+1]

	/* consult goto table to find next state */
	Yyn = YyR1[Yyn]
	Yyg := YyPgo[Yyn]
	Yyj := Yyg + YyS[Yyp].yys + 1

	if Yyj >= YyLast {
		Yystate = YyAct[Yyg]
	} else {
		Yystate = YyAct[Yyj]
		if YyChk[Yystate] != -Yyn {
			Yystate = YyAct[Yyg]
		}
	}
	// dummy call; replaced with literal code
	switch Yynt {

	}
	goto Yystack /* stack new state and value */
}
